name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

  # TweetBook
  # API
    - name: Navigate API Project
      run: cd TweetBookAPI
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
   
  # Integration Test
    - name: Navigate Test Project
      run: cd TweetBook.IntegrationTests
    - name: Test
      run: dotnet test --no-restore --verbosity normal
